// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvavkg_p2TBNgAUNlyVcFiKi05RsfPqE',
    appId: '1:833973645622:web:746eecf9fb8ab8c0e00397',
    messagingSenderId: '833973645622',
    projectId: 'mockmate-ai-106',
    authDomain: 'mockmate-ai-106.firebaseapp.com',
    storageBucket: 'mockmate-ai-106.firebasestorage.app',
    measurementId: 'G-7JPSXSK4BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsconhFIAv4k8qDJh8jfI7yeolqKtNljQ',
    appId: '1:833973645622:android:bcc1fa521e9a60ade00397',
    messagingSenderId: '833973645622',
    projectId: 'mockmate-ai-106',
    storageBucket: 'mockmate-ai-106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgEQbi31Vhae94xA7Ef53G7n0DNSrGqM',
    appId: '1:833973645622:ios:e0ac5ba906baf75ae00397',
    messagingSenderId: '833973645622',
    projectId: 'mockmate-ai-106',
    storageBucket: 'mockmate-ai-106.firebasestorage.app',
    iosClientId: '833973645622-02030asr5cul51hg0ee8bllnd9g80f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockmateAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGgEQbi31Vhae94xA7Ef53G7n0DNSrGqM',
    appId: '1:833973645622:ios:e0ac5ba906baf75ae00397',
    messagingSenderId: '833973645622',
    projectId: 'mockmate-ai-106',
    storageBucket: 'mockmate-ai-106.firebasestorage.app',
    iosClientId: '833973645622-02030asr5cul51hg0ee8bllnd9g80f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockmateAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsvavkg_p2TBNgAUNlyVcFiKi05RsfPqE',
    appId: '1:833973645622:web:c66671caec7f7d63e00397',
    messagingSenderId: '833973645622',
    projectId: 'mockmate-ai-106',
    authDomain: 'mockmate-ai-106.firebaseapp.com',
    storageBucket: 'mockmate-ai-106.firebasestorage.app',
    measurementId: 'G-6Z5PDJ0847',
  );
}
